from autogen import UserProxyAgent

# Helper agents
client_proxy = UserProxyAgent(
    name="client",
    system_message="You are client who want best interior design possible",
    human_input_mode="NEVER",
    max_consecutive_auto_reply=1,
    is_termination_msg=lambda x: x.get("content", "") and x.get("content", "").rstrip().rstrip('.').endswith("TERMINATE")
)

code_executor = UserProxyAgent(
    name="code_executor",
    human_input_mode="NEVER",
    code_execution_config={
        "use_docker": False
    }
)

from autogen import config_list_from_json

llm_config = {
    'timeout': 600,
    'cache_seed': 45,
    'config_list': config_list_from_json(
        env_or_file='OAI_CONFIG_LIST',
        filter_dict={
            'model': ['gpt4']}),
    'temperature': 0
}

llm_config_4v = {
    'timeout': 600,
    'cache_seed': 45,
    'config_list': config_list_from_json(
        env_or_file='OAI_CONFIG_LIST',
        filter_dict = {
            'model': ['gpt4v']}),
    'max_tokens': 1000,
    'temperature': 0   
}

from autogen.agentchat.contrib.multimodal_conversable_agent import MultimodalConversableAgent
# Interior Designer agent
from autogen import AssistantAgent
interior_designer = AssistantAgent(
    name='interior_designer',
    system_message="""
    You are a skilled interior designer.
    Your task is to develop a room design based on a client's photos and their specific requirements.
    
    Your responsibilities are divided into two primary areas:
    
    1. Create Initial Design:
       - Consider the room's layout, including window and door placements, to develop visually appealing and functional spaces.
       - Ensure the design is user-friendly and comfortable.
       - Provide your design proposal in a detailed yet concise paragraph, capturing all essential elements.
    
    2. Review and Feedback:
       - Evaluate the interior visualizations generated by the 'interior_visualizer'.
       - Provide detailed feedback focusing on how closely these visualizations match your initial design intentions, pay closer attention to furniture count, placement, materials and color. 
       - Suggest specific adjustments to better align the visualization with the original design concept. Include changes in colors, materials, furniture placement, and other design elements.
       - Be strict.
       - If the visualization is at least 95% accurate to your initial design, confirm that no further changes are needed and the task is complete by saying 'TERMINATE'.
    """,
    llm_config=llm_config
)

from autogen.agentchat.contrib.capabilities.vision_capability import VisionCapability
vision_capability = VisionCapability(lmm_config=llm_config_4v)
vision_capability.add_to_agent(interior_designer)

interior_visualizer = AssistantAgent(
    name='interior_visualizer',
    system_message="""
    You are an expert AI, specializing in interior design visualization and text-to-image prompt engineering.

    Your tasks involve:
    1. A photo of the room that needs a new design.
    2. Detailed interior design description provided by an interior designer.
    3. A reference photo showing the design style the user wants.
    4. Feedback from a critic, who checks if your visualizations match the designer's original description.
    
    Your responsibilities are divided into two primary areas:
    
    1. Visualize the Design
        - Convert detailed design descriptions into simplified, effective prompts suitable for image generation systems. 
            Utilize techniques such as weighted elements (e.g., (luxurious textures:1.2)) and textual inversion embeddings (e.g., embedding:custom_wood) to emphasize key features. 
            Implement randomness for creative variations by including choices in your prompt, e.g., {minimalist|baroque|modern}.
            Reformat design elements into a list of keywords and phrases, grouped by attributes such as color, material, and placement, ensuring precision and effectiveness in visualization. 
            Focus on capturing essential details such as color, material, and placement to ensure accuracy and utility in image generation.
        
        - Use the simplified prompt and reference photos to create a visualization of the interior design.
        
    2. Adjust the Visualization:
        Continuously refine the design visualization based on the interior designer’s feedback. 
        Modify the simplified prompt as needed to achieve the best possible result.
    """,
    llm_config=llm_config
)

import json
import replicate
def create_interior_design_visualization(
    empty_room_image_url:str,
    design_style_image_url:str, 
    design_prompt:str):
    
    input = {
        "workflow_json": json.dumps(
            get_formatted_image_generation_workflow(
                empty_room_image_url, 
                design_style_image_url, 
                design_prompt)),
        "randomise_seeds": False,
        "return_temp_files": False,
        "optimise_output_images": True,
        "optimise_output_images_quality": 80
    }

    output = replicate.run(
        "fofr/any-comfyui-workflow:2a29afb3f346f7cb910345ee73f8abd1f64c33a9c4254c638abc4d56b7c23749",
        input=input
    )
    
    return f'Interior design visualization is ready. You can find it here: <img {output[0]}>'

from autogen import GroupChat, GroupChatManager
chat = GroupChat([client_proxy, interior_designer, interior_visualizer, code_executor], messages=[], max_round=10)
chat_manager = GroupChatManager(groupchat=chat, llm_config={'config_list': llm_config['config_list']})

from autogen import register_function
register_function(
    create_interior_design_visualization,
    caller=interior_visualizer,
    executor=code_executor,
    name='create_interior_design_visualization',
    description='Generate interior design visualization based on photo of the room that needs a new design, prompt, reference photo showing the design style the user wants'
)